name: Continuous Integration

on:
  push:
    branches: [v2]
  pull_request:
    branches: [v2]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    name: Lint and Format

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Copy .env.example to .env
        run: cp .env.example .env

      - name: Run ESLint
        run: npm run lint

      - name: Check formatting with Prettier
        run: npm run format -- --check

      - name: TypeScript compilation check
        run: npx tsc --noEmit

  build-test:
    runs-on: ubuntu-latest
    name: Build and Test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Copy .env.example to .env
        run: cp .env.example .env

      - name: Build application
        run: npm run build
        env:
          NEXT_TELEMETRY_DISABLED: 1
          DATABASE_URL: postgresql://test:test@localhost:5432/test
          AUTH_SECRET: test-secret-for-build
          AUTH_URL: http://localhost:3000
          GITHUB_CLIENT_ID: test-client-id
          GITHUB_CLIENT_SECRET: test-client-secret

      - name: Check for build artifacts
        run: |
          if [ ! -d ".next" ]; then
            echo "Build failed: .next directory not found"
            exit 1
          fi
          echo "Build successful: .next directory found"

  dependency-check:
    runs-on: ubuntu-latest
    name: Dependency Security Check

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run security audit
        run: |
          echo "Running npm audit..."
          if npm audit --audit-level high; then
            echo "✅ No high-severity vulnerabilities found"
          else
            echo "⚠️ High-severity vulnerabilities found, but continuing..."
            echo "Run 'npm audit fix' to resolve issues"
            # Don't fail the workflow for audit issues, just warn
          fi

      - name: Check for outdated packages
        run: npm outdated || true

  database-migration-test:
    runs-on: ubuntu-latest
    name: Database Migration Test

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_DB: test_snippets
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Wait for PostgreSQL
        run: |
          echo "Waiting for PostgreSQL to be ready..."
          until pg_isready -h localhost -p 5432 -U test; do
            echo "Still waiting for PostgreSQL..."
            sleep 2
          done
          echo "✅ PostgreSQL is ready"

      - name: Test database migrations
        run: npm run db:push
        env:
          DATABASE_URL: postgresql://test:test@localhost:5432/test_snippets

  summary:
    runs-on: ubuntu-latest
    name: CI Summary
    needs:
      [
        lint-and-format,
        build-test,
        docker-build-test,
        dependency-check,
        database-migration-test,
      ]
    if: always()

    steps:
      - name: Check results
        run: |
          echo "## CI Results Summary" >> $GITHUB_STEP_SUMMARY
          echo "| Job | Status |" >> $GITHUB_STEP_SUMMARY
          echo "|-----|--------|" >> $GITHUB_STEP_SUMMARY
          echo "| Lint and Format | ${{ needs.lint-and-format.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Build and Test | ${{ needs.build-test.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Docker Build Test | ${{ needs.docker-build-test.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Dependency Check | ${{ needs.dependency-check.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Database Migration Test | ${{ needs.database-migration-test.result }} |" >> $GITHUB_STEP_SUMMARY

          # Only fail on critical job failures (lint, build, database)
          if [[ "${{ needs.lint-and-format.result }}" == "failure" || 
                "${{ needs.build-test.result }}" == "failure" || 
                "${{ needs.database-migration-test.result }}" == "failure" ]]; then
            echo "❌ CI pipeline failed - critical jobs failed"
            exit 1
          elif [[ "${{ needs.docker-build-test.result }}" == "failure" || 
                  "${{ needs.dependency-check.result }}" == "failure" ]]; then
            echo "⚠️ CI pipeline completed with warnings - non-critical jobs failed"
            echo "Please review Docker build and dependency issues"
          else
            echo "✅ All CI checks passed"
          fi
