name: Deploy Server to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -p ${{ secrets.VPS_PORT || 22 }} -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts
        chmod 600 ~/.ssh/known_hosts

    - name: Test SSH connection
      run: |
        ssh -p ${{ secrets.VPS_PORT || 22 }} -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "echo SSH connection successful"

    - name: Copy server directory to VPS
      run: |
        rsync -avz --delete -e "ssh -p ${{ secrets.VPS_PORT || 22 }} -i ~/.ssh/id_rsa" ./server/ ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/var/www/snippetslibrary/server

    - name: Execute deployment script on VPS
      run: |
        ssh -p ${{ secrets.VPS_PORT || 22 }} -i ~/.ssh/id_rsa ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "bash /var/www/snippetslibrary/deploy.sh"